### ISSUE TITLE
The generic AmbassadorInstallation fails to install

### ISSUE THREAD

**Issue by jaydeland** [datawire/ambassador-operator#26]
https://github.com/datawire/ambassador-operator/blob/master/deploy/crds/getambassador.io_v2_ambassadorinstallation_cr.yaml

The AmbassadorInstallation "ambassador" is invalid:
* spec.helmValues.image: Invalid value: "object": spec.helmValues.image in body must be of type string: "object"
* spec.helmValues.namespace: Invalid value: "object": spec.helmValues.namespace in body must be of type string: "object"
* spec.helmValues.service: Invalid value: "object": spec.helmValues.service in body must be of type string: "object"

**Comment by inercia** [comment]
Hi @jaydeland, this issue should be fixed on the HEAD of the Operator (it was fixed in https://github.com/datawire/ambassador-operator/pull/22). Please give it a try.

**Comment by jaydeland** [comment]
I just moved forward with the other syntax since it's more compact and easy to read

**Comment by inercia** [comment]
Then I will close this issue. Please reopen if you consider necessary.
